// Mirrors REQUIRED_KYC_FIELDS in frontend/app.js — the same per-client-type
// obligatory KYC fields, with a page reference added so a detected gap can
// say where in the questionnaire it lives. Keep both lists in sync: this one
// drives the server-side completeness check (services/kycGapCheck.service.js),
// the frontend one drives the editable KYC form and its "missing" highlight.
const REQUIRED_KYC_FIELDS = {
  Individual: [
    { key: 'firstName',        label: 'First Name',            page: 'Page 1 — Personal Details' },
    { key: 'lastName',         label: 'Last Name',              page: 'Page 1 — Personal Details' },
    { key: 'dob',              label: 'Date of Birth',          page: 'Page 1 — Personal Details' },
    { key: 'nationality',      label: 'Nationality',            page: 'Page 1 — Personal Details' },
    { key: 'residency',        label: 'Residency',              page: 'Page 1 — Personal Details' },
    { key: 'taxResidency',     label: 'Tax Residency',          page: 'Page 2 — Tax & Identification' },
    { key: 'taxId',            label: 'Tax ID / SSN',           page: 'Page 2 — Tax & Identification' },
    { key: 'passportNumber',   label: 'Passport Number',        page: 'Page 2 — Tax & Identification' },
    { key: 'passportExpiry',   label: 'Passport Expiry',        page: 'Page 2 — Tax & Identification' },
    { key: 'address',          label: 'Address',                page: 'Page 2 — Tax & Identification' },
    { key: 'employmentStatus', label: 'Employment Status',      page: 'Page 3 — Financial Profile' },
    { key: 'occupation',       label: 'Occupation',              page: 'Page 3 — Financial Profile' },
    { key: 'annualIncome',     label: 'Annual Income',          page: 'Page 3 — Financial Profile' },
    { key: 'sourceOfWealth',   label: 'Source of Wealth',       page: 'Page 3 — Financial Profile' },
  ],
  Corporate: [
    { key: 'legalName',            label: 'Legal Name',              page: 'Page 1 — Entity Details' },
    { key: 'tradingName',          label: 'Trading Name',            page: 'Page 1 — Entity Details' },
    { key: 'registrationNumber',   label: 'Registration Number',     page: 'Page 1 — Entity Details' },
    { key: 'registrationDate',     label: 'Registration Date',       page: 'Page 1 — Entity Details' },
    { key: 'registrationCountry',  label: 'Registration Country',    page: 'Page 1 — Entity Details' },
    { key: 'jurisdiction',         label: 'Jurisdiction',            page: 'Page 1 — Entity Details' },
    { key: 'address',              label: 'Registered Address',      page: 'Page 1 — Entity Details' },
    { key: 'businessType',         label: 'Business Type',           page: 'Page 2 — Business Profile' },
    { key: 'industry',             label: 'Industry',                page: 'Page 2 — Business Profile' },
    { key: 'website',              label: 'Website',                 page: 'Page 2 — Business Profile' },
    { key: 'purpose',              label: 'Purpose of Account',      page: 'Page 2 — Business Profile' },
    { key: 'annualTurnover',       label: 'Annual Turnover',         page: 'Page 3 — Financial Profile' },
    { key: 'netAssets',            label: 'Net Assets',              page: 'Page 3 — Financial Profile' },
    { key: 'employees',            label: 'Employees',               page: 'Page 3 — Financial Profile' },
  ],
  Domiciliary: [
    { key: 'legalName',                   label: 'Legal Name',                     page: 'Page 1 — Entity Details' },
    { key: 'registrationNumber',          label: 'Registration Number',            page: 'Page 1 — Entity Details' },
    { key: 'registrationDate',            label: 'Registration Date',              page: 'Page 1 — Entity Details' },
    { key: 'registrationCountry',         label: 'Registration Country',           page: 'Page 1 — Entity Details' },
    { key: 'jurisdiction',                label: 'Jurisdiction',                   page: 'Page 1 — Entity Details' },
    { key: 'address',                     label: 'Registered Address',             page: 'Page 1 — Entity Details' },
    { key: 'purpose',                     label: 'Purpose of Account',             page: 'Page 2 — Beneficial Ownership' },
    { key: 'beneficialOwnerName',         label: 'Beneficial Owner Name',          page: 'Page 2 — Beneficial Ownership' },
    { key: 'beneficialOwnerNationality',  label: 'Beneficial Owner Nationality',   page: 'Page 2 — Beneficial Ownership' },
    { key: 'sourceOfWealth',              label: 'Source of Wealth',               page: 'Page 3 — Financial Profile' },
    { key: 'netAssets',                   label: 'Net Assets',                     page: 'Page 3 — Financial Profile' },
  ],
  Foundation: [
    { key: 'foundationName',       label: 'Foundation Name',                       page: 'Page 1 — Entity Details' },
    { key: 'registrationNumber',   label: 'Registration Number',                   page: 'Page 1 — Entity Details' },
    { key: 'registrationDate',     label: 'Registration Date',                     page: 'Page 1 — Entity Details' },
    { key: 'registrationCountry',  label: 'Registration Country',                  page: 'Page 1 — Entity Details' },
    { key: 'jurisdiction',         label: 'Jurisdiction',                          page: 'Page 1 — Entity Details' },
    { key: 'address',              label: 'Registered Address',                    page: 'Page 1 — Entity Details' },
    { key: 'purpose',              label: 'Purpose / Object of Foundation',        page: 'Page 2 — Beneficial Ownership' },
    { key: 'founderName',          label: 'Founder Name',                          page: 'Page 2 — Beneficial Ownership' },
    { key: 'beneficialOwnerName',  label: 'Beneficial Owner / Board Member Name',  page: 'Page 2 — Beneficial Ownership' },
    { key: 'sourceOfWealth',       label: 'Source of Wealth',                      page: 'Page 3 — Financial Profile' },
    { key: 'netAssets',            label: 'Net Assets',                            page: 'Page 3 — Financial Profile' },
  ],
  Trust: [
    { key: 'trustName',          label: 'Trust Name',                    page: 'Page 1 — Trust Details' },
    { key: 'trustDeedDate',      label: 'Trust Deed Date',               page: 'Page 1 — Trust Details' },
    { key: 'jurisdiction',       label: 'Jurisdiction',                  page: 'Page 1 — Trust Details' },
    { key: 'settlorName',        label: 'Settlor Name',                  page: 'Page 2 — Parties' },
    { key: 'settlorNationality', label: 'Settlor Nationality',           page: 'Page 2 — Parties' },
    { key: 'trusteeName',        label: 'Trustee Name',                  page: 'Page 2 — Parties' },
    { key: 'protectorName',      label: 'Protector Name (if appointed)', page: 'Page 2 — Parties' },
    { key: 'beneficiaries',      label: 'Beneficiaries',                 page: 'Page 2 — Parties' },
    { key: 'purpose',            label: 'Purpose of Trust',              page: 'Page 3 — Financial Profile' },
    { key: 'sourceOfWealth',     label: 'Source of Wealth',              page: 'Page 3 — Financial Profile' },
    { key: 'netAssets',          label: 'Net Assets',                    page: 'Page 3 — Financial Profile' },
  ],
};

module.exports = { REQUIRED_KYC_FIELDS };
