const test = require('node:test');
const assert = require('node:assert/strict');
const mongoose = require('mongoose');
const { MongoMemoryServer } = require('mongodb-memory-server');
const Client = require('../models/Client');
const KycCorrection = require('../models/KycCorrection');
const { REQUIRED_KYC_FIELDS } = require('../config/kycRequiredFields');
const {
  saveKycFields,
  submitKycFields,
  approveKycCorrection,
  rejectKycCorrection,
  flagFieldIncorrect,
  refreshVerificationFlag,
  OPEN_CORRECTION_STATUSES,
} = require('../services/kycGapCheck.service');

test('KYC correction Save vs Submit KYC lifecycle', { timeout: 120_000 }, async (t) => {
  const mongo = await MongoMemoryServer.create();
  const mongoUri = mongo.getUri('kyc-correction-workflow-test');
  t.after(async () => {
    if (mongoose.connection.readyState) await mongoose.disconnect();
    await mongo.stop();
  });
  await mongoose.connect(mongoUri, { autoIndex: false });

  async function freshClient(overrides = {}) {
    const clientId = `CLT-${Math.floor(Math.random() * 1e9)}`;
    const client = await Client.create({
      clientId,
      name: 'Test Client',
      email: `${clientId.toLowerCase()}@example.test`,
      type: 'Individual',
      rm: 'RM-1',
      kyc: {},
      ...overrides,
    });
    return client;
  }

  async function openCorrectionFor(client, fieldKey, label, status = 'pending') {
    return KycCorrection.create({
      mandateId: client.clientId,
      clientId: client.clientId,
      issue: `Missing: ${label}`,
      page: '1. Personal Information',
      status,
      autoGenerated: true,
      fieldKey,
      everFilled: status !== 'pending',
    });
  }

  await t.test('fresh correction is pending', async () => {
    const client = await freshClient();
    const correction = await openCorrectionFor(client, 'firstName', 'Vorname(n) (*)');
    assert.equal(correction.status, 'pending');
  });

  await t.test('Compliance cannot flag a draft that only has historical submission provenance', async () => {
    const client = await freshClient({
      kyc: { firstName: 'Alice' },
      kycSubmittedBy: 'rm',
      kycStatus: 'draft',
      kycAwaitingVerification: false,
    });

    await assert.rejects(() => flagFieldIncorrect(client._id, 'firstName'), (err) => {
      assert.equal(err.status, 409);
      return true;
    });

    const persisted = await Client.findById(client._id);
    assert.equal(persisted.kyc.firstName, 'Alice');
  });

  await t.test('saveKycFields moves pending -> saved, never resubmitted/corrected', async () => {
    const client = await freshClient();
    await openCorrectionFor(client, 'firstName', 'Vorname(n) (*)');
    await Client.updateOne({ _id: client._id }, { $set: { 'kyc.firstName': 'Alice' } });

    const result = await saveKycFields(client._id, ['firstName'], 'rm');
    assert.equal(result.updated, 1);

    const correction = await KycCorrection.findOne({ clientId: client.clientId, fieldKey: 'firstName' });
    assert.equal(correction.status, 'saved');
    assert.equal(correction.everFilled, true);
    assert.ok(correction.history.some((h) => h.status === 'saved' && h.actor === 'rm'));

    // Value persisted independent of correction status — simulates "survives reload".
    const persisted = await Client.findById(client._id);
    assert.equal(persisted.kyc.firstName, 'Alice');
  });

  await t.test('saveKycFields by a compliance actor remains a saved draft', async () => {
    const client = await freshClient();
    await openCorrectionFor(client, 'firstName', 'Vorname(n) (*)');
    await Client.updateOne({ _id: client._id }, { $set: { 'kyc.firstName': 'Alice' } });

    await saveKycFields(client._id, ['firstName'], 'compliance');
    const correction = await KycCorrection.findOne({ clientId: client.clientId, fieldKey: 'firstName' });
    assert.equal(correction.status, 'saved');
  });

  await t.test('submitKycFields moves saved -> resubmitted, not straight to corrected', async () => {
    const client = await freshClient();
    await openCorrectionFor(client, 'firstName', 'Vorname(n) (*)');
    await Client.updateOne({ _id: client._id }, { $set: { 'kyc.firstName': 'Alice' } });
    await saveKycFields(client._id, ['firstName'], 'rm');

    await submitKycFields(client._id, ['firstName'], 'rm');
    const correction = await KycCorrection.findOne({ clientId: client.clientId, fieldKey: 'firstName' });
    assert.equal(correction.status, 'resubmitted');
    assert.ok(correction.history.some((h) => h.status === 'resubmitted' && h.actor === 'rm'));
  });

  await t.test('submitKycFields also advances a never-saved pending field directly', async () => {
    const client = await freshClient();
    await openCorrectionFor(client, 'firstName', 'Vorname(n) (*)');
    await Client.updateOne({ _id: client._id }, { $set: { 'kyc.firstName': 'Alice' } });

    await submitKycFields(client._id, ['firstName'], 'rm');
    const correction = await KycCorrection.findOne({ clientId: client.clientId, fieldKey: 'firstName' });
    assert.equal(correction.status, 'resubmitted');
  });

  await t.test('approveKycCorrection only accepts resubmitted, produces corrected', async () => {
    const client = await freshClient();
    const pending = await openCorrectionFor(client, 'firstName', 'Vorname(n) (*)');
    await Client.updateOne({ _id: client._id }, { $set: { 'kyc.firstName': 'Alice' } });

    await assert.rejects(() => approveKycCorrection(pending._id), (err) => {
      assert.equal(err.status, 409);
      return true;
    });

    await saveKycFields(client._id, ['firstName'], 'rm');
    await submitKycFields(client._id, ['firstName'], 'rm');
    const approved = await approveKycCorrection(pending._id);
    assert.equal(approved.status, 'corrected');
    assert.equal(approved.rejectionReason, undefined);
  });

  await t.test('full deny -> re-save -> re-submit -> approve loop on the same field', async () => {
    const client = await freshClient();
    const correction = await openCorrectionFor(client, 'firstName', 'Vorname(n) (*)');
    await Client.updateOne({ _id: client._id }, { $set: { 'kyc.firstName': 'Alice' } });
    await saveKycFields(client._id, ['firstName'], 'rm');
    await submitKycFields(client._id, ['firstName'], 'rm');

    const denied = await rejectKycCorrection(correction._id, 'Name does not match passport');
    assert.equal(denied.status, 'needs_correction');
    assert.equal(denied.rejectionReason, 'Name does not match passport');

    // RM's field is cleared and glows again — must go through save then submit once more.
    const afterDeny = await Client.findById(client._id);
    assert.equal(afterDeny.kyc.firstName, '');

    await Client.updateOne({ _id: client._id }, { $set: { 'kyc.firstName': 'Alice Fixed' } });
    const secondSave = await saveKycFields(client._id, ['firstName'], 'rm');
    assert.equal(secondSave.updated, 1);
    let current = await KycCorrection.findById(correction._id);
    assert.equal(current.status, 'saved');

    const secondSubmit = await submitKycFields(client._id, ['firstName'], 'rm');
    assert.equal(secondSubmit.updated, 1);
    current = await KycCorrection.findById(correction._id);
    assert.equal(current.status, 'resubmitted');

    const finalApproval = await approveKycCorrection(correction._id);
    assert.equal(finalApproval.status, 'corrected');
    assert.equal(finalApproval.rejectionReason, undefined);
  });

  await t.test('two independent fields: denying one does not touch the other', async () => {
    const client = await freshClient();
    const legalNameCorrection = await openCorrectionFor(client, 'firstName', 'Vorname(n) (*)');
    const beneficialOwnerNameCorrection = await openCorrectionFor(client, 'lastName', 'Nachname (*)');
    await Client.updateOne({ _id: client._id }, { $set: { 'kyc.firstName': 'Alice', 'kyc.lastName': 'Smith' } });

    await saveKycFields(client._id, ['firstName', 'lastName'], 'rm');
    await submitKycFields(client._id, ['firstName', 'lastName'], 'rm');

    await approveKycCorrection(beneficialOwnerNameCorrection._id);
    await rejectKycCorrection(legalNameCorrection._id, 'Spelling');

    const approvedStillCorrected = await KycCorrection.findById(beneficialOwnerNameCorrection._id);
    assert.equal(approvedStillCorrected.status, 'corrected');
    const deniedOne = await KycCorrection.findById(legalNameCorrection._id);
    assert.equal(deniedOne.status, 'needs_correction');
  });

  await t.test('refreshVerificationFlag stays false while any field is only saved', async () => {
    // Every required field has a real value, so the only thing blocking
    // sign-off is the still-open 'saved' correction on lastName.
    const allValues = Object.fromEntries(
      REQUIRED_KYC_FIELDS.Individual
        .map((f) => [f.key, `${f.key} value`])
    );
    const client = await freshClient({
      kyc: allValues,
      kycSubmittedBy: 'rm',
      kycAwaitingVerification: true,
    });
    const correction = await openCorrectionFor(client, 'lastName', 'Nachname (*)');
    await saveKycFields(client._id, ['lastName'], 'rm');

    assert.ok(OPEN_CORRECTION_STATUSES.includes('saved'));
    const stillSaved = await KycCorrection.findById(correction._id);
    assert.equal(stillSaved.status, 'saved');
    const cleared = await refreshVerificationFlag(client._id);
    assert.equal(cleared, false);

    // Field-level approval makes the form eligible, but only the explicit
    // whole-form verify endpoint may clear under-review.
    await submitKycFields(client._id, ['lastName'], 'rm');
    await approveKycCorrection(correction._id);
    const eligibleAfterApproval = await refreshVerificationFlag(client._id);
    assert.equal(eligibleAfterApproval, true);
    const persisted = await Client.findById(client._id);
    assert.equal(persisted.kycAwaitingVerification, true);
  });
});
