const mongoose = require('mongoose');

// A flagged KYC data issue on a client's mandate that the RM must fix and
// resubmit, and Compliance then confirms as corrected.
const kycCorrectionSchema = new mongoose.Schema({
  mandateId: { type: String },
  clientId:  { type: String, required: true },
  issue:     { type: String, required: true },
  page:      { type: String },
  status:    { type: String, enum: ['pending', 'resubmitted', 'corrected'], default: 'pending' },

  // Set on corrections generated automatically by comparing a client's KYC
  // data against REQUIRED_KYC_FIELDS (see services/kycGapCheck.service.js) —
  // fieldKey lets that sync find and auto-resolve/reopen its own corrections
  // as fields get filled in or cleared, without touching manually-created ones.
  autoGenerated: { type: Boolean, default: false },
  fieldKey:      { type: String },
}, { timestamps: true });

module.exports = mongoose.model('KycCorrection', kycCorrectionSchema);
