const mongoose = require('mongoose');

// A flagged KYC data issue on a client's single shared KYC record — one item
// per field. 'pending' = never had a value (first-time gap). 'needs_correction'
// = had a value before (submitted once already) but is now flagged wrong or
// cleared again — deliberately kept distinct from 'pending' so the UI never
// tells a user "this is brand new" when it's really "this was rejected."
// 'saved' = the RM has entered and saved a corrected value, but has NOT yet
// pressed Submit KYC — the value is persisted but Compliance hasn't been
// asked to review it. 'resubmitted' = the field's been submitted and is
// awaiting Compliance verification. 'corrected' = closed after Compliance
// explicitly confirms it. Saving must never jump straight to
// 'resubmitted'/'corrected' — only Submit KYC advances 'saved' to
// 'resubmitted', and only a separate Compliance action writes 'corrected'.
const kycCorrectionSchema = new mongoose.Schema({
  mandateId: { type: String },
  clientId:  { type: String, required: true },
  issue:     { type: String, required: true },
  page:      { type: String },
  status:    { type: String, enum: ['pending', 'needs_correction', 'saved', 'resubmitted', 'corrected'], default: 'pending' },

  // Set on corrections generated automatically by comparing a client's KYC
  // data against REQUIRED_KYC_FIELDS (see services/kycGapCheck.service.js) —
  // fieldKey lets that sync find and reopen its own corrections as fields go
  // missing again, without touching manually-created ones.
  autoGenerated: { type: Boolean, default: false },
  fieldKey:      { type: String },
  // Has this field ever held a real submitted value? Distinguishes a true
  // first-time gap ('pending') from a field that's gone missing/flagged again
  // after already being filled in once ('needs_correction').
  everFilled:    { type: Boolean, default: false },
  // Set by Compliance on denial (see updateKycCorrectionStatus), shown back
  // to the RM alongside the reopened field. Cleared on the next approval.
  rejectionReason: { type: String },
  // Append-only transition log — one entry per save/submit/flag/approve/deny
  // — so the full original-value → rejected → corrected → reviewed trail
  // stays reconstructable without a parallel audit system.
  history: [new mongoose.Schema({
    status: { type: String, required: true },
    actor:  { type: String },
    reason: { type: String },
    at:     { type: Date, default: Date.now },
  }, { _id: false })],
  // Short-lived ownership token for the standalone-Mongo compensation path.
  // Replica-set deployments use transactions and never need this marker.
  workflowMutationId: { type: String },
}, { timestamps: true });

// One automatically generated workflow item per canonical field. Manual
// corrections are intentionally outside this constraint.
kycCorrectionSchema.index(
  { clientId: 1, fieldKey: 1 },
  {
    unique: true,
    partialFilterExpression: { autoGenerated: true, fieldKey: { $type: 'string' } },
    name: 'uniq_auto_kyc_correction_field',
  }
);

module.exports = mongoose.model('KycCorrection', kycCorrectionSchema);
