const mongoose = require('mongoose');

// A flagged KYC data issue on a client's single shared KYC record — one item
// per field. 'pending' = never had a value (first-time gap). 'needs_correction'
// = had a value before (submitted once already) but is now flagged wrong or
// cleared again — deliberately kept distinct from 'pending' so the UI never
// tells a user "this is brand new" when it's really "this was rejected."
// 'resubmitted' = the field's been filled in and is awaiting Compliance
// verification (set when an RM/client submits). 'corrected' = closed —
// either Compliance confirmed it, or Compliance itself was the submitter
// (self-verifying, no separate review step needed).
const kycCorrectionSchema = new mongoose.Schema({
  mandateId: { type: String },
  clientId:  { type: String, required: true },
  issue:     { type: String, required: true },
  page:      { type: String },
  status:    { type: String, enum: ['pending', 'needs_correction', 'resubmitted', 'corrected'], default: 'pending' },

  // Set on corrections generated automatically by comparing a client's KYC
  // data against REQUIRED_KYC_FIELDS (see services/kycGapCheck.service.js) —
  // fieldKey lets that sync find and reopen its own corrections as fields go
  // missing again, without touching manually-created ones.
  autoGenerated: { type: Boolean, default: false },
  fieldKey:      { type: String },
  // Has this field ever held a real submitted value? Distinguishes a true
  // first-time gap ('pending') from a field that's gone missing/flagged again
  // after already being filled in once ('needs_correction').
  everFilled:    { type: Boolean, default: false },
}, { timestamps: true });

module.exports = mongoose.model('KycCorrection', kycCorrectionSchema);
