const { test, expect } = require('@playwright/test');
const { deleteClientsByEmailPattern } = require('../helpers/dbTestUsers');

const headersFor = (token) => ({ Authorization: `Bearer ${token}` });

async function login(request, email, role) {
  const response = await request.post('/api/auth/login', {
    data: { email, password: 'Demo1234!', role },
  });
  expect(response.ok()).toBe(true);
  return (await response.json()).token;
}

function validAnswersFor(task) {
  return Object.fromEntries(task.sections.flatMap((section) => section.fields).map((field) => {
    if (field.type === 'date') return [field.key, '1990-01-01'];
    if (field.type === 'select') return [field.key, field.options[0]];
    return [field.key, `${field.key} value`];
  }));
}

function statusesFor(corrections, clientId, fieldKeys) {
  return Object.fromEntries(fieldKeys.map((key) => [
    key,
    corrections.find((c) => c.clientId === clientId && c.fieldKey === key && c.autoGenerated)?.status,
  ]));
}

// Walks the exact RM -> Compliance -> RM loop from the correction workflow
// spec: Save must only ever reach 'saved' (never resolve/approve/submit a
// correction on its own), Submit KYC is the only action that hands a saved
// field to Compliance as 'resubmitted', and only Compliance's explicit
// Confirm/Deny can produce 'corrected' or send a field back to the RM.
test.describe('KYC correction Save/Submit lifecycle', () => {
  let clientEmail;

  test.afterEach(async () => {
    if (clientEmail) await deleteClientsByEmailPattern(clientEmail);
  });

  test('Save never resolves a correction; only Submit KYC and Compliance review do', async ({ request }) => {
    const [rmToken, complianceToken] = await Promise.all([
      login(request, 'rm@demo.com', 'rm'),
      login(request, 'compliance@demo.com', 'compliance'),
    ]);
    const rmHeaders = headersFor(rmToken);
    const complianceHeaders = headersFor(complianceToken);
    clientEmail = `kyc-correction-lifecycle-${Date.now()}@e2e.local`;

    // 1. Real initial KYC submission so the client has real submitted values.
    const invite = await request.post('/api/contracts/invite', {
      headers: rmHeaders,
      data: {
        clientName: 'KYC Correction Lifecycle',
        clientEmail,
        templateId: 'e2e-no-file',
        templateName: 'E2E Contract',
        fieldValues: { client_type: 'individual' },
        createClientAccount: false,
        requiredDocuments: [],
      },
    });
    expect(invite.ok()).toBe(true);

    const clients = await (await request.get('/api/clients', { headers: rmHeaders })).json();
    const client = clients.find((c) => c.email === clientEmail);
    expect(client).toBeTruthy();
    const tasks = await (await request.get('/api/kyc-tasks', { headers: rmHeaders })).json();
    const task = tasks.find((t) => t.clientRef === client._id);
    expect(task).toBeTruthy();

    const initialAnswers = validAnswersFor(task);
    const initialSave = await request.post(`/api/kyc-tasks/${task._id}/save`, {
      headers: rmHeaders,
      data: { answers: initialAnswers },
    });
    expect(initialSave.ok()).toBe(true);
    expect((await initialSave.json()).status).toBe('pending');

    const initialSubmit = await request.post(`/api/kyc-tasks/${task._id}/complete`, {
      headers: rmHeaders,
      data: { answers: initialAnswers },
    });
    expect(initialSubmit.ok()).toBe(true);
    expect((await initialSubmit.json()).status).toBe('under_review');

    // 2. Compliance flags several previously-good fields as wrong.
    const flaggedKeys = ['firstName', 'lastName', 'dateOfBirth', 'nationality'];
    for (const fieldKey of flaggedKeys) {
      const flag = await request.post('/api/corrections/kyc/flag', {
        headers: complianceHeaders,
        data: { clientId: client.clientId, fieldKey },
      });
      expect(flag.ok()).toBe(true);
    }
    let corrections = await (await request.get('/api/corrections/kyc', { headers: rmHeaders })).json();
    expect(statusesFor(corrections, client.clientId, flaggedKeys)).toEqual({
      firstName: 'needs_correction', lastName: 'needs_correction', dateOfBirth: 'needs_correction', nationality: 'needs_correction',
    });
    const clientsAfterFlag = await (await request.get('/api/clients', { headers: rmHeaders })).json();
    const kycAwaitingVerificationBeforeSave = clientsAfterFlag.find((c) => c._id === client._id).kycAwaitingVerification;

    // 3. RM saves a partial subset — Save must move only the saved fields to
    // 'saved', never past it, and must leave the rest untouched.
    const partialSave = await request.post(`/api/kyc-tasks/${task._id}/save`, {
      headers: rmHeaders,
      data: { answers: { firstName: 'Corrected First', lastName: 'Corrected Last' } },
    });
    expect(partialSave.ok()).toBe(true);

    corrections = await (await request.get('/api/corrections/kyc', { headers: rmHeaders })).json();
    expect(statusesFor(corrections, client.clientId, flaggedKeys)).toEqual({
      firstName: 'saved', lastName: 'saved', dateOfBirth: 'needs_correction', nationality: 'needs_correction',
    });

    // Value is persisted immediately (survives reload) even though the
    // correction has not been submitted to Compliance yet — and Save must
    // not touch the awaiting-verification flag either way.
    const afterPartialSave = await (await request.get('/api/clients', { headers: rmHeaders })).json();
    const clientAfterPartialSave = afterPartialSave.find((c) => c._id === client._id);
    expect(clientAfterPartialSave.kyc.firstName).toBe('Corrected First');
    expect(clientAfterPartialSave.kycAwaitingVerification).toBe(kycAwaitingVerificationBeforeSave);

    const partialCorrectionSubmit = await request.post('/api/corrections/kyc/resubmit-section', {
      headers: rmHeaders,
      data: {
        clientId: client.clientId,
        values: { firstName: 'Corrected First', lastName: 'Corrected Last' },
      },
    });
    expect(partialCorrectionSubmit.status()).toBe(409);
    const partialCorrectionBody = await partialCorrectionSubmit.json();
    expect(partialCorrectionBody.details.missingFields).toEqual(expect.arrayContaining(['dateOfBirth', 'nationality']));

    corrections = await (await request.get('/api/corrections/kyc', { headers: rmHeaders })).json();
    expect(statusesFor(corrections, client.clientId, flaggedKeys)).toEqual({
      firstName: 'saved', lastName: 'saved', dateOfBirth: 'needs_correction', nationality: 'needs_correction',
    });

    // 4. RM saves the rest.
    const restSave = await request.post(`/api/kyc-tasks/${task._id}/save`, {
      headers: rmHeaders,
      data: { answers: { dateOfBirth: '1985-05-05', nationality: 'Corrected Nationality' } },
    });
    expect(restSave.ok()).toBe(true);
    corrections = await (await request.get('/api/corrections/kyc', { headers: rmHeaders })).json();
    expect(statusesFor(corrections, client.clientId, flaggedKeys)).toEqual({
      firstName: 'saved', lastName: 'saved', dateOfBirth: 'saved', nationality: 'saved',
    });

    // 5. RM presses Submit KYC — only now do the saved fields go to Compliance.
    const correctedAnswers = {
      ...initialAnswers,
      firstName: 'Corrected First',
      lastName: 'Corrected Last',
      dateOfBirth: '1985-05-05',
      nationality: 'Corrected Nationality',
    };
    const submit = await request.post(`/api/kyc-tasks/${task._id}/complete`, {
      headers: rmHeaders,
      data: { answers: correctedAnswers },
    });
    expect(submit.ok()).toBe(true);
    expect((await submit.json()).status).toBe('under_review');
    corrections = await (await request.get('/api/corrections/kyc', { headers: rmHeaders })).json();
    expect(statusesFor(corrections, client.clientId, flaggedKeys)).toEqual({
      firstName: 'resubmitted', lastName: 'resubmitted', dateOfBirth: 'resubmitted', nationality: 'resubmitted',
    });
    const afterSubmit = await (await request.get('/api/clients', { headers: rmHeaders })).json();
    expect(afterSubmit.find((c) => c._id === client._id).kycAwaitingVerification).toBe(true);

    // 6. Compliance confirms three, denies one with a reason.
    const idFor = (fieldKey) => corrections.find((c) => c.clientId === client.clientId && c.fieldKey === fieldKey && c.autoGenerated)._id;
    for (const fieldKey of ['firstName', 'lastName', 'dateOfBirth']) {
      const approve = await request.post(`/api/corrections/kyc/${idFor(fieldKey)}/status`, {
        headers: complianceHeaders,
        data: { status: 'corrected' },
      });
      expect(approve.ok()).toBe(true);
    }
    const deny = await request.post(`/api/corrections/kyc/${idFor('nationality')}/status`, {
      headers: complianceHeaders,
      data: { status: 'needs_correction', reason: 'Does not match passport nationality' },
    });
    expect(deny.ok()).toBe(true);
    const denyBody = await deny.json();
    expect(denyBody.status).toBe('needs_correction');
    expect(denyBody.rejectionReason).toBe('Does not match passport nationality');

    corrections = await (await request.get('/api/corrections/kyc', { headers: rmHeaders })).json();
    expect(statusesFor(corrections, client.clientId, flaggedKeys)).toEqual({
      firstName: 'corrected', lastName: 'corrected', dateOfBirth: 'corrected', nationality: 'needs_correction',
    });
    // Denying nationality must not touch the three already-approved fields.
    const afterDenyClients = await (await request.get('/api/clients', { headers: rmHeaders })).json();
    const clientAfterDeny = afterDenyClients.find((c) => c._id === client._id);
    expect(clientAfterDeny.kyc.firstName).toBe('Corrected First');
    expect(clientAfterDeny.kyc.nationality).toBe('');

    // 7. RM fixes the denied field again: save then submit, full loop.
    const refix = await request.post(`/api/kyc-tasks/${task._id}/save`, {
      headers: rmHeaders,
      data: { answers: { nationality: 'Fixed Nationality' } },
    });
    expect(refix.ok()).toBe(true);
    corrections = await (await request.get('/api/corrections/kyc', { headers: rmHeaders })).json();
    expect(corrections.find((c) => c.clientId === client.clientId && c.fieldKey === 'nationality').status).toBe('saved');

    const finalAnswers = { ...correctedAnswers, nationality: 'Fixed Nationality' };
    const resubmit = await request.post(`/api/kyc-tasks/${task._id}/complete`, {
      headers: rmHeaders,
      data: { answers: finalAnswers },
    });
    expect(resubmit.ok()).toBe(true);
    expect((await resubmit.json()).status).toBe('under_review');
    corrections = await (await request.get('/api/corrections/kyc', { headers: rmHeaders })).json();
    expect(corrections.find((c) => c.clientId === client.clientId && c.fieldKey === 'nationality').status).toBe('resubmitted');

    // 8. Compliance approves the fixed field — correction fully closes.
    const finalApprove = await request.post(`/api/corrections/kyc/${idFor('nationality')}/status`, {
      headers: complianceHeaders,
      data: { status: 'corrected' },
    });
    expect(finalApprove.ok()).toBe(true);

    corrections = await (await request.get('/api/corrections/kyc', { headers: complianceHeaders })).json();
    const openForClient = corrections.filter((c) =>
      c.clientId === client.clientId && c.autoGenerated && c.status !== 'corrected'
    );
    expect(openForClient).toHaveLength(0);

    // Approving the last field-level correction is not whole-form Compliance
    // sign-off. The case remains under review until the explicit verify action.
    const finalClients = await (await request.get('/api/clients', { headers: complianceHeaders })).json();
    const finalClient = finalClients.find((c) => c._id === client._id);
    expect(finalClient.kycAwaitingVerification).toBe(true);
    expect(finalClient.kycStatus).toBe('under_review');

    const verify = await request.post(`/api/kyc-tasks/client/${encodeURIComponent(client.clientId)}/verify`, {
      headers: complianceHeaders,
    });
    expect(verify.ok()).toBe(true);
    expect((await verify.json()).status).toBe('approved');

    const approvedClients = await (await request.get('/api/clients', { headers: complianceHeaders })).json();
    const approvedClient = approvedClients.find((c) => c._id === client._id);
    expect(approvedClient.kycAwaitingVerification).toBe(false);
    expect(approvedClient.kycStatus).toBe('approved');
  });
});
