const KycCorrection = require('../models/KycCorrection');
const { REQUIRED_KYC_FIELDS } = require('../config/kycRequiredFields');

// Pure gap detection: makes sure every currently-missing required field has
// an OPEN correction tracking it. Never resolves anything itself — resolving
// only happens through an explicit submission (submitKycFields) or a manual
// Compliance action, never just because a value silently appeared.
async function syncKycCorrectionsForClient(client) {
  const fields = REQUIRED_KYC_FIELDS[client.type] || [];
  if (!fields.length) return;

  const kyc = client.kyc || {};
  const missingKeys = new Set(fields.filter(f => !String(kyc[f.key] || '').trim()).map(f => f.key));

  const existing = await KycCorrection.find({ clientId: client.clientId, autoGenerated: true });
  const existingByKey = new Map(existing.map(c => [c.fieldKey, c]));

  for (const f of fields) {
    if (!missingKeys.has(f.key)) continue;
    const existingC = existingByKey.get(f.key);
    if (!existingC) {
      await KycCorrection.create({
        clientId: client.clientId, mandateId: client.clientId,
        fieldKey: f.key, issue: `Missing: ${f.label}`, page: f.page,
        status: 'pending', autoGenerated: true, everFilled: false,
      });
    } else if (existingC.status === 'corrected') {
      // Was resolved before, is blank again — this field has a submission
      // history, so reopen it as a correction rather than a fresh 'pending'.
      existingC.status = 'needs_correction';
      await existingC.save();
    }
    // else: already open (pending/needs_correction/resubmitted) — leave as is.
  }
}

// Called right after real values land in client.kyc (initial KYC Task
// completion, or a Corrections "resubmit section" action) — moves whichever
// of those fields had an open correction into the right next state. A
// Compliance submitter closes it outright (self-verifying); an RM/client
// submitter hands it to Compliance for verification instead.
async function submitKycFields(client, filledKeys, submittedByRole) {
  if (!filledKeys || !filledKeys.length) return;
  const kyc = client.kyc || {};
  const targetStatus = submittedByRole === 'compliance' ? 'corrected' : 'resubmitted';

  const corrections = await KycCorrection.find({
    clientId: client.clientId, fieldKey: { $in: filledKeys }, autoGenerated: true,
    status: { $in: ['pending', 'needs_correction'] },
  });
  for (const c of corrections) {
    if (!String(kyc[c.fieldKey] || '').trim()) continue; // still empty — nothing submitted
    c.status = targetStatus;
    c.everFilled = true;
    await c.save();
  }
}

// Compliance flags an already-filled field as wrong: clears the value (so it
// reads as empty + needs re-entry) and reopens/creates its correction as
// 'needs_correction' rather than the misleading first-time 'pending'.
async function flagFieldIncorrect(client, fieldKey) {
  const fields = REQUIRED_KYC_FIELDS[client.type] || [];
  const fieldDef = fields.find(f => f.key === fieldKey);
  if (!fieldDef) return null;

  if (client.kyc) {
    client.kyc[fieldKey] = '';
    client.markModified('kyc');
    await client.save();
  }

  let correction = await KycCorrection.findOne({ clientId: client.clientId, fieldKey, autoGenerated: true });
  if (correction) {
    correction.status = 'needs_correction';
    correction.everFilled = true;
    await correction.save();
  } else {
    correction = await KycCorrection.create({
      clientId: client.clientId, mandateId: client.clientId,
      fieldKey, issue: `Missing: ${fieldDef.label}`, page: fieldDef.page,
      status: 'needs_correction', autoGenerated: true, everFilled: true,
    });
  }
  return correction;
}

// Clears the "awaiting Compliance verification" flag once nothing is left
// open for this client — called after any correction resolves.
async function refreshVerificationFlag(client) {
  const openCount = await KycCorrection.countDocuments({
    clientId: client.clientId, autoGenerated: true,
    status: { $in: ['pending', 'needs_correction', 'resubmitted'] },
  });
  if (openCount === 0 && client.kycAwaitingVerification) {
    client.kycAwaitingVerification = false;
    await client.save();
  }
}

module.exports = { syncKycCorrectionsForClient, submitKycFields, flagFieldIncorrect, refreshVerificationFlag };
