const KycCorrection = require('../models/KycCorrection');
const { REQUIRED_KYC_FIELDS } = require('../config/kycRequiredFields');

// Compares a client's KYC data against the obligatory fields for its type and
// keeps KycCorrection in sync: opens (or reopens) one per currently-missing
// field, and auto-resolves any it previously opened once that field is filled
// in — so Corrections never keeps showing a gap that's already been fixed.
// Only touches corrections it created itself (autoGenerated:true); anything
// Compliance flagged by hand is left alone.
async function syncKycCorrectionsForClient(client) {
  const fields = REQUIRED_KYC_FIELDS[client.type] || [];
  if (!fields.length) return;

  const kyc = client.kyc || {};
  const missingKeys = new Set(fields.filter(f => !String(kyc[f.key] || '').trim()).map(f => f.key));

  const existing = await KycCorrection.find({ clientId: client.clientId, autoGenerated: true });
  const existingByKey = new Map(existing.map(c => [c.fieldKey, c]));

  for (const c of existing) {
    if (!missingKeys.has(c.fieldKey) && c.status !== 'corrected') {
      c.status = 'corrected';
      await c.save();
    }
  }

  for (const f of fields) {
    if (!missingKeys.has(f.key)) continue;
    const existingC = existingByKey.get(f.key);
    if (!existingC) {
      await KycCorrection.create({
        clientId: client.clientId, mandateId: client.clientId,
        fieldKey: f.key, issue: `Missing: ${f.label}`, page: f.page,
        status: 'pending', autoGenerated: true,
      });
    } else if (existingC.status === 'corrected') {
      // Was filled in before, is blank again — reopen the same item instead
      // of piling up a duplicate.
      existingC.status = 'pending';
      await existingC.save();
    }
    // else: already open (pending/resubmitted) — leave as is.
  }
}

module.exports = { syncKycCorrectionsForClient };
