const mongoose = require('mongoose');
const { randomUUID } = require('crypto');
const Client = require('../models/Client');
const KycCorrection = require('../models/KycCorrection');
const { REQUIRED_KYC_FIELDS } = require('../config/kycRequiredFields');

const OPEN_CORRECTION_STATUSES = ['pending', 'needs_correction', 'saved', 'resubmitted'];

const hasValue = (value) => String(value ?? '').trim().length > 0;

function clientIdentity(clientOrId) {
  if (!clientOrId) return null;
  return clientOrId._id || clientOrId;
}

async function readCurrentClient(clientOrId, session = null) {
  const id = clientIdentity(clientOrId);
  if (!id) return null;
  const query = Client.findById(id);
  if (session) query.session(session);
  return query;
}

function isTransactionUnsupported(err) {
  return err?.code === 20
    || err?.codeName === 'IllegalOperation'
    || /transaction numbers are only allowed|does not support transactions/i.test(String(err?.message || ''));
}

function workflowError(message, status = 409) {
  const err = new Error(message);
  err.status = status;
  return err;
}

// Replica sets get a real cross-collection transaction. Local standalone
// MongoDB rejects transaction writes with code 20, so callers provide an
// idempotent correction-first fallback with guarded compensation. This keeps
// the normal local workflow usable without ever persisting a blank Client.kyc
// field before its corresponding correction exists.
async function runTransactionOrFallback(work, fallback) {
  const session = await mongoose.startSession();
  try {
    let result;
    await session.withTransaction(async () => {
      result = await work(session);
    });
    return result;
  } catch (err) {
    if (isTransactionUnsupported(err)) {
      return fallback();
    }
    throw err;
  } finally {
    await session.endSession();
  }
}

function correctionState(correction) {
  if (!correction) return null;
  return {
    status: correction.status,
    everFilled: correction.everFilled,
    issue: correction.issue,
    page: correction.page,
  };
}

async function restoreCorrectionAfterFailedClear(correction, prior, mutationId) {
  if (!correction) return;
  if (!prior) {
    await KycCorrection.deleteOne({ _id: correction._id, workflowMutationId: mutationId });
    return;
  }
  await KycCorrection.updateOne(
    { _id: correction._id, workflowMutationId: mutationId },
    { $set: prior, $unset: { workflowMutationId: 1 } }
  );
}

async function finishCorrectionMutation(correctionId, mutationId) {
  await KycCorrection.updateOne(
    { _id: correctionId, workflowMutationId: mutationId },
    { $unset: { workflowMutationId: 1 } }
  );
  return KycCorrection.findById(correctionId);
}

// Keep historical auto-generated corrections aligned when the canonical KYC
// schema changes. Only fields removed from the schema cease to be actionable;
// every field still displayed in KYC must remain non-empty for submission.
async function reconcileKycCorrectionDefinitions(clientOrId) {
  const client = await readCurrentClient(clientOrId);
  if (!client) return { updated: 0 };

  const fields = REQUIRED_KYC_FIELDS[client.type] || [];
  const fieldsByKey = new Map(fields.map((field) => [field.key, field]));
  const corrections = await KycCorrection.find({ clientId: client.clientId, autoGenerated: true });
  let updated = 0;

  for (const correction of corrections) {
    const field = fieldsByKey.get(correction.fieldKey);
    const expectedPage = field?.page || 'Obsolete schema field';
    const expectedIssue = field
      ? `Missing: ${field.label}`
      : `Obsolete KYC field: ${correction.fieldKey || 'unknown'}`;
    const shouldClose = !field;
    const updates = {};

    if (correction.page !== expectedPage) updates.page = expectedPage;
    if (correction.issue !== expectedIssue) updates.issue = expectedIssue;
    if (shouldClose && correction.status !== 'corrected') updates.status = 'corrected';

    if (Object.keys(updates).length) {
      await KycCorrection.updateOne({ _id: correction._id }, { $set: updates });
      updated += 1;
    }
  }

  return { updated };
}

async function closeFilledAutoGaps(client) {
  const fields = REQUIRED_KYC_FIELDS[client.type] || [];
  let closed = 0;

  for (const field of fields) {
    if (!hasValue(client.kyc?.[field.key])) continue;
    const result = await KycCorrection.updateOne(
      {
        clientId: client.clientId,
        fieldKey: field.key,
        autoGenerated: true,
        workflowMutationId: { $exists: false },
        // Only a 'pending' row (never flagged, never rejected) is eligible
        // for this silent reconciliation — a filled value there really is
        // just a stale/false "missing" gap. A 'needs_correction' row means
        // Compliance explicitly rejected this field; its resolution must
        // always go through save → submit → Compliance review (never a
        // side effect of a value merely being present), the same rule that
        // governs every other path into 'corrected'.
        status: 'pending',
      },
      {
        $set: {
          // This is reconciliation, not a Compliance approval: an open
          // "missing" row whose canonical value was already present is a
          // false/stale gap and must not block whole-form sign-off.
          status: 'corrected',
          everFilled: true,
          issue: `Missing: ${field.label}`,
          page: field.page,
        },
        $push: { history: { status: 'corrected', actor: 'system-reconcile', at: new Date() } },
      }
    );
    closed += result.modifiedCount || 0;
  }

  return closed;
}

// Gap sync always reads Client.kyc from MongoDB. Callers may pass a document
// for convenience, but its Mixed snapshot is never trusted. The final fresh
// pass is deliberate: if two disjoint submissions cross between the initial
// read and an upsert, whichever scan inserts last also observes and closes the
// now-filled false gap.
async function syncKycCorrectionsForClient(clientOrId) {
  let client = await readCurrentClient(clientOrId);
  if (!client) return { missing: 0, created: 0, reopened: 0, closed: 0 };

  // A correction for a field the canonical schema no longer contains can never
  // be answered — the questionnaire does not render it — so left open it would
  // pin the task in "To Complete" forever and block whole-form sign-off. Retire
  // those first, on the same write paths that already reconcile stale gaps.
  await reconcileKycCorrectionDefinitions(client);
  client = await readCurrentClient(client._id) || client;

  const fields = REQUIRED_KYC_FIELDS[client.type] || [];
  if (!fields.length) return { missing: 0, created: 0, reopened: 0, closed: 0 };

  let created = 0;
  let reopened = 0;
  let closed = await closeFilledAutoGaps(client);

  for (const field of fields) {
    // Only a mandatory question is a gap when blank. Raising one for each of
    // the optional questions would put ~90 "missing" rows on every mandate and
    // bury the handful that actually need answering.
    if (field.required === false) continue;
    if (hasValue(client.kyc?.[field.key])) continue;

    // Re-read the one canonical record immediately before creating a gap.
    // This avoids acting on the caller's or the first pass's stale Mixed data.
    const current = await readCurrentClient(client._id);
    if (!current || current.type !== client.type || hasValue(current.kyc?.[field.key])) continue;

    let result;
    try {
      result = await KycCorrection.updateOne(
        { clientId: current.clientId, fieldKey: field.key, autoGenerated: true },
        {
          $setOnInsert: {
            mandateId: current.clientId,
            issue: `Missing: ${field.label}`,
            page: field.page,
            status: 'pending',
            everFilled: false,
          },
        },
        { upsert: true }
      );
    } catch (err) {
      if (err?.code !== 11000) throw err;
      result = { upsertedCount: 0 };
    }

    if (result.upsertedCount) {
      created += 1;
      continue;
    }

    const reopenNeedsCorrection = await KycCorrection.updateOne(
      {
        clientId: current.clientId,
        fieldKey: field.key,
        autoGenerated: true,
        status: 'corrected',
        everFilled: true,
      },
      { $set: { status: 'needs_correction', issue: `Missing: ${field.label}`, page: field.page } }
    );
    const reopenPending = await KycCorrection.updateOne(
      {
        clientId: current.clientId,
        fieldKey: field.key,
        autoGenerated: true,
        status: 'corrected',
        everFilled: { $ne: true },
      },
      { $set: { status: 'pending', issue: `Missing: ${field.label}`, page: field.page } }
    );
    reopened += (reopenNeedsCorrection.modifiedCount || 0) + (reopenPending.modifiedCount || 0);
  }

  // This reconciliation closes an upsert that raced with a concurrent field
  // submission. It also refreshes the returned missing count from DB state.
  client = await readCurrentClient(client._id);
  if (!client) return { missing: 0, created, reopened, closed };
  closed += await closeFilledAutoGaps(client);
  const currentFields = REQUIRED_KYC_FIELDS[client.type] || [];
  const missing = currentFields.filter(
    (field) => field.required !== false && !hasValue(client.kyc?.[field.key])
  ).length;

  return { missing, created, reopened, closed };
}

// Draft save only — persists whichever previously-open corrections now have
// a value, without ever handing them to Compliance. An RM/client save can
// only reach 'saved'; it must never advance a correction to 'resubmitted' or
// 'corrected' on its own, regardless of which actor is editing the draft.
async function saveKycFields(clientOrId, filledKeys, actorRole) {
  if (!filledKeys || !filledKeys.length) return { updated: 0 };
  const client = await readCurrentClient(clientOrId);
  if (!client) return { updated: 0 };

  const fieldKeys = new Set((REQUIRED_KYC_FIELDS[client.type] || []).map((field) => field.key));
  const presentKeys = [...new Set(filledKeys)].filter(
    (key) => fieldKeys.has(key) && hasValue(client.kyc?.[key])
  );
  if (!presentKeys.length) return { updated: 0 };

  const targetStatus = 'saved';
  const result = await KycCorrection.updateMany(
    {
      clientId: client.clientId,
      fieldKey: { $in: presentKeys },
      autoGenerated: true,
      workflowMutationId: { $exists: false },
      status: { $in: ['pending', 'needs_correction'] },
    },
    {
      $set: { status: targetStatus, everFilled: true },
      $push: { history: { status: targetStatus, actor: actorRole, at: new Date() } },
    }
  );
  return { updated: result.modifiedCount || 0 };
}

// Move only corrections whose canonical value currently exists. The Client
// is re-read after the dotted-path write made by the controller, so a stale
// caller document cannot mark a blank field as resubmitted/corrected. This is
// the Submit KYC transition — a 'saved' draft (or a field filled directly in
// the same submit, without a prior explicit Save) advances to 'resubmitted'
// for Compliance to review. A Compliance-authored submission is the
// exception: Compliance is already the reviewer, so there is no one left to
// review it — it self-verifies straight to 'corrected', same as a Compliance
// Save does.
async function submitKycFields(clientOrId, filledKeys, submittedByRole) {
  if (!filledKeys || !filledKeys.length) return { updated: 0 };
  const client = await readCurrentClient(clientOrId);
  if (!client) return { updated: 0 };

  const fieldKeys = new Set((REQUIRED_KYC_FIELDS[client.type] || []).map((field) => field.key));
  const presentKeys = [...new Set(filledKeys)].filter(
    (key) => fieldKeys.has(key) && hasValue(client.kyc?.[key])
  );
  if (!presentKeys.length) return { updated: 0 };

  // A submission always lands as 'resubmitted' — awaiting review — no matter
  // who submitted it. Only Compliance's explicit confirm writes 'corrected'.
  const targetStatus = 'resubmitted';
  const result = await KycCorrection.updateMany(
    {
      clientId: client.clientId,
      fieldKey: { $in: presentKeys },
      autoGenerated: true,
      workflowMutationId: { $exists: false },
      status: { $in: ['pending', 'needs_correction', 'saved'] },
    },
    {
      $set: { status: targetStatus, everFilled: true },
      ...(targetStatus === 'corrected' ? { $unset: { rejectionReason: 1 } } : {}),
      $push: { history: { status: targetStatus, actor: submittedByRole, at: new Date() } },
    }
  );
  return { updated: result.modifiedCount || 0 };
}

// Compliance flags an already-filled field as wrong. The dotted canonical
// value clear, correction upsert, verification flag and audit entry commit as
// one transaction or none of them commit.
// Compliance reviews a submitted KYC and may flag several fields in one
// sitting. The first flag deliberately sends the questionnaire back to the RM
// (kycStatus -> 'draft'), which would otherwise make every subsequent flag in
// that same review fail the "must be under review" guard. A draft that already
// carries an open correction is exactly "a submitted KYC currently being
// corrected", so it stays flaggable — while a draft with no corrections (an RM
// simply editing, or historical submission provenance only) does not.
async function canFlagFields(client) {
  const workflowStatus = client.kycStatus
    || (client.kycSubmittedBy
      ? client.kycAwaitingVerification ? 'under_review' : 'approved'
      : 'draft');
  if (['under_review', 'approved'].includes(workflowStatus)) return true;
  if (!client.kycSubmittedBy) return false;
  const openCount = await KycCorrection.countDocuments({
    clientId: client.clientId,
    autoGenerated: true,
    status: { $in: ['pending', 'needs_correction', 'saved', 'resubmitted'] },
  });
  return openCount > 0;
}

async function flagFieldIncorrect(clientOrId, fieldKey) {
  const transactionWork = async (session) => {
    const client = await readCurrentClient(clientOrId, session);
    if (!client) throw workflowError('Client not found', 404);

    const fieldDef = (REQUIRED_KYC_FIELDS[client.type] || []).find((field) => field.key === fieldKey);
    if (!fieldDef) throw workflowError('Unknown field for this client type', 400);
    if (!(await canFlagFields(client))) {
      throw workflowError('Only a KYC submitted for review or already approved can be flagged', 409);
    }
    if (!hasValue(client.kyc?.[fieldKey])) {
      throw workflowError('Only a currently filled KYC field can be flagged', 409);
    }

    const correction = await KycCorrection.findOneAndUpdate(
      { clientId: client.clientId, fieldKey, autoGenerated: true },
      {
        $set: {
          mandateId: client.clientId,
          issue: `Missing: ${fieldDef.label}`,
          page: fieldDef.page,
          status: 'needs_correction',
          everFilled: true,
        },
        $setOnInsert: { clientId: client.clientId, fieldKey, autoGenerated: true },
        $push: { history: { status: 'needs_correction', actor: 'compliance', at: new Date() } },
      },
      { upsert: true, new: true, session, runValidators: true }
    );

    const clientUpdate = await Client.updateOne(
      { _id: client._id, type: client.type },
      {
        $set: {
          [`kyc.${fieldKey}`]: '',
          kycAwaitingVerification: false,
          kycStatus: 'draft',
        },
        $unset: { kycApprovedAt: 1, kycApprovedBy: 1 },
        $push: {
          auditTrail: {
            action: `KYC field "${fieldDef.label}" flagged incorrect by Compliance`,
            user: 'Compliance',
            time: new Date().toLocaleString(),
            type: 'requested',
          },
        },
      },
      { session, runValidators: true }
    );
    if (clientUpdate.matchedCount !== 1) {
      throw workflowError('Client legal form changed while the field was being flagged', 409);
    }

    return correction;
  };

  const fallbackWork = async () => {
    const client = await readCurrentClient(clientOrId);
    if (!client) throw workflowError('Client not found', 404);
    const fieldDef = (REQUIRED_KYC_FIELDS[client.type] || []).find((field) => field.key === fieldKey);
    if (!fieldDef) throw workflowError('Unknown field for this client type', 400);
    if (!(await canFlagFields(client))) {
      throw workflowError('Only a KYC submitted for review or already approved can be flagged', 409);
    }
    const currentValue = client.kyc?.[fieldKey];
    if (!hasValue(currentValue)) {
      const existing = await KycCorrection.findOne({
        clientId: client.clientId,
        fieldKey,
        autoGenerated: true,
        status: 'needs_correction',
      });
      if (existing) return existing;
      throw workflowError('Only a currently filled KYC field can be flagged', 409);
    }

    const mutationId = randomUUID();
    const before = await KycCorrection.findOne({ clientId: client.clientId, fieldKey, autoGenerated: true }).lean();
    const correction = await KycCorrection.findOneAndUpdate(
      { clientId: client.clientId, fieldKey, autoGenerated: true },
      {
        $set: {
          mandateId: client.clientId,
          issue: `Missing: ${fieldDef.label}`,
          page: fieldDef.page,
          status: 'needs_correction',
          everFilled: true,
          workflowMutationId: mutationId,
        },
        $setOnInsert: { clientId: client.clientId, fieldKey, autoGenerated: true },
        $push: { history: { status: 'needs_correction', actor: 'compliance', at: new Date() } },
      },
      { upsert: true, new: true, runValidators: true }
    );

    try {
      const update = await Client.updateOne(
        { _id: client._id, type: client.type, [`kyc.${fieldKey}`]: currentValue },
        {
          $set: { [`kyc.${fieldKey}`]: '', kycAwaitingVerification: false, kycStatus: 'draft' },
          $unset: { kycApprovedAt: 1, kycApprovedBy: 1 },
          $push: {
            auditTrail: {
              action: `KYC field "${fieldDef.label}" flagged incorrect by Compliance`,
              user: 'Compliance',
              time: new Date().toLocaleString(),
              type: 'requested',
            },
          },
        },
        { runValidators: true }
      );
      if (update.matchedCount !== 1) {
        const latest = await Client.findById(client._id);
        if (latest?.type === client.type && !hasValue(latest.kyc?.[fieldKey])) {
          return finishCorrectionMutation(correction._id, mutationId);
        }
        throw workflowError('KYC field changed while it was being flagged; review the latest value', 409);
      }
      return finishCorrectionMutation(correction._id, mutationId);
    } catch (err) {
      await restoreCorrectionAfterFailedClear(correction, correctionState(before), mutationId);
      throw err;
    }
  };

  return runTransactionOrFallback(transactionWork, fallbackWork);
}

// The other half of flagFieldIncorrect: Compliance explicitly signs off on a
// field that was never flagged in the first place — same audit trail (who
// confirmed it, when) as a field that actually went through a correction
// cycle, instead of that trail only existing for fields that had a problem.
// No canonical value is touched, so unlike flagging this never needs the
// transaction/compensation dance — a single atomic upsert is enough.
async function confirmFieldCorrect(clientOrId, fieldKey) {
  const client = await readCurrentClient(clientOrId);
  if (!client) throw workflowError('Client not found', 404);
  const fieldDef = (REQUIRED_KYC_FIELDS[client.type] || []).find((field) => field.key === fieldKey);
  if (!fieldDef) throw workflowError('Unknown field for this client type', 400);
  const workflowStatus = client.kycStatus
    || (client.kycSubmittedBy
      ? client.kycAwaitingVerification ? 'under_review' : 'approved'
      : 'draft');
  if (!['under_review', 'approved'].includes(workflowStatus)) {
    throw workflowError('Only a KYC submitted for review or already approved can be confirmed field-by-field', 409);
  }
  if (!hasValue(client.kyc?.[fieldKey])) {
    throw workflowError('Only a currently filled KYC field can be confirmed', 409);
  }
  return KycCorrection.findOneAndUpdate(
    { clientId: client.clientId, fieldKey, autoGenerated: true },
    {
      $set: { mandateId: client.clientId, issue: `Missing: ${fieldDef.label}`, page: fieldDef.page, status: 'corrected', everFilled: true },
      $unset: { rejectionReason: 1 },
      $setOnInsert: { clientId: client.clientId, fieldKey, autoGenerated: true },
      $push: { history: { status: 'corrected', actor: 'compliance', at: new Date() } },
    },
    { upsert: true, new: true, runValidators: true }
  );
}

async function rejectKycCorrection(correctionId, reason) {
  const transactionWork = async (session) => {
    const correction = await KycCorrection.findById(correctionId).session(session);
    if (!correction) throw workflowError('KYC correction not found', 404);
    if (!correction.autoGenerated || !correction.fieldKey) {
      throw workflowError('Only a canonical KYC field correction can be rejected', 400);
    }

    const client = await Client.findOne({ clientId: correction.clientId }).session(session);
    if (!client) throw workflowError('Client not found for this correction', 409);
    const fieldDef = (REQUIRED_KYC_FIELDS[client.type] || []).find(
      (field) => field.key === correction.fieldKey
    );
    if (!fieldDef) throw workflowError('Correction field is not part of the current legal form', 409);

    if (correction.status === 'needs_correction' && !hasValue(client.kyc?.[correction.fieldKey])) {
      return correction;
    }
    if (!hasValue(client.kyc?.[correction.fieldKey])) {
      throw workflowError('A blank pending field cannot be rejected as previously filled', 409);
    }

    correction.status = 'needs_correction';
    correction.everFilled = true;
    correction.issue = `Missing: ${fieldDef.label}`;
    correction.page = fieldDef.page;
    correction.rejectionReason = reason || '';
    correction.history.push({ status: 'needs_correction', actor: 'compliance', reason: reason || '', at: new Date() });
    await correction.save({ session });

    const update = await Client.updateOne(
      { _id: client._id, type: client.type },
      {
        $set: {
          [`kyc.${correction.fieldKey}`]: '',
          kycAwaitingVerification: false,
          kycStatus: 'draft',
        },
        $unset: { kycApprovedAt: 1, kycApprovedBy: 1 },
        $push: {
          auditTrail: {
            action: `KYC field "${fieldDef.label}" marked needs correction`,
            user: 'Compliance',
            time: new Date().toLocaleString(),
            type: 'requested',
          },
        },
      },
      { session, runValidators: true }
    );
    if (update.matchedCount !== 1) {
      throw workflowError('Client legal form changed while the correction was being rejected', 409);
    }
    return correction;
  };

  const fallbackWork = async () => {
    const correction = await KycCorrection.findById(correctionId);
    if (!correction) throw workflowError('KYC correction not found', 404);
    if (!correction.autoGenerated || !correction.fieldKey) {
      throw workflowError('Only a canonical KYC field correction can be rejected', 400);
    }

    const client = await Client.findOne({ clientId: correction.clientId });
    if (!client) throw workflowError('Client not found for this correction', 409);
    const fieldDef = (REQUIRED_KYC_FIELDS[client.type] || []).find(
      (field) => field.key === correction.fieldKey
    );
    if (!fieldDef) throw workflowError('Correction field is not part of the current legal form', 409);

    const currentValue = client.kyc?.[correction.fieldKey];
    if (correction.status === 'needs_correction' && !hasValue(currentValue)) return correction;
    if (!hasValue(currentValue)) {
      throw workflowError('A blank pending field cannot be rejected as previously filled', 409);
    }

    const mutationId = randomUUID();
    const prior = correctionState(correction);
    const claimed = await KycCorrection.findOneAndUpdate(
      { _id: correction._id, status: correction.status },
      {
        $set: {
          status: 'needs_correction',
          everFilled: true,
          issue: `Missing: ${fieldDef.label}`,
          page: fieldDef.page,
          rejectionReason: reason || '',
          workflowMutationId: mutationId,
        },
        $push: { history: { status: 'needs_correction', actor: 'compliance', reason: reason || '', at: new Date() } },
      },
      { new: true, runValidators: true }
    );
    if (!claimed) throw workflowError('KYC correction changed while it was being rejected', 409);

    try {
      const update = await Client.updateOne(
        { _id: client._id, type: client.type, [`kyc.${correction.fieldKey}`]: currentValue },
        {
          $set: { [`kyc.${correction.fieldKey}`]: '', kycAwaitingVerification: false, kycStatus: 'draft' },
          $unset: { kycApprovedAt: 1, kycApprovedBy: 1 },
          $push: {
            auditTrail: {
              action: `KYC field "${fieldDef.label}" marked needs correction`,
              user: 'Compliance',
              time: new Date().toLocaleString(),
              type: 'requested',
            },
          },
        },
        { runValidators: true }
      );
      if (update.matchedCount !== 1) {
        const latest = await Client.findById(client._id);
        if (latest?.type === client.type && !hasValue(latest.kyc?.[correction.fieldKey])) {
          return finishCorrectionMutation(claimed._id, mutationId);
        }
        throw workflowError('KYC field changed while the correction was being rejected', 409);
      }
      return finishCorrectionMutation(claimed._id, mutationId);
    } catch (err) {
      await restoreCorrectionAfterFailedClear(claimed, prior, mutationId);
      throw err;
    }
  };

  return runTransactionOrFallback(transactionWork, fallbackWork);
}

// Compliance may confirm only a field that was actually resubmitted and is
// still non-empty in the canonical Client.kyc record. This transaction makes
// the value check, correction transition and audit indivisible.
async function approveKycCorrection(correctionId) {
  const transactionWork = async (session) => {
    const correction = await KycCorrection.findById(correctionId).session(session);
    if (!correction) throw workflowError('KYC correction not found', 404);
    if (correction.status !== 'resubmitted') {
      throw workflowError('Only a resubmitted KYC field can be marked corrected', 409);
    }
    if (!correction.autoGenerated || !correction.fieldKey) {
      throw workflowError('Only a canonical KYC field correction can be confirmed', 400);
    }

    const client = await Client.findOne({ clientId: correction.clientId }).session(session);
    if (!client) throw workflowError('Client not found for this correction', 409);
    const fieldDef = (REQUIRED_KYC_FIELDS[client.type] || []).find(
      (field) => field.key === correction.fieldKey
    );
    if (!fieldDef) throw workflowError('Correction field is not part of the current legal form', 409);
    if (!hasValue(client.kyc?.[correction.fieldKey])) {
      throw workflowError('A blank KYC field cannot be marked corrected', 409);
    }

    correction.status = 'corrected';
    correction.everFilled = true;
    correction.issue = `Missing: ${fieldDef.label}`;
    correction.page = fieldDef.page;
    correction.rejectionReason = undefined;
    correction.history.push({ status: 'corrected', actor: 'compliance', at: new Date() });
    await correction.save({ session });

    const update = await Client.updateOne(
      { _id: client._id, type: client.type },
      {
        $push: {
          auditTrail: {
            action: `KYC field "${fieldDef.label}" marked corrected`,
            user: 'Compliance',
            time: new Date().toLocaleString(),
            type: 'approved',
          },
        },
      },
      { session, runValidators: true }
    );
    if (update.matchedCount !== 1) {
      throw workflowError('Client legal form changed while the correction was being confirmed', 409);
    }
    return correction;
  };

  const fallbackWork = async () => {
    const correction = await KycCorrection.findById(correctionId);
    if (!correction) throw workflowError('KYC correction not found', 404);
    if (correction.status !== 'resubmitted') {
      throw workflowError('Only a resubmitted KYC field can be marked corrected', 409);
    }
    if (!correction.autoGenerated || !correction.fieldKey) {
      throw workflowError('Only a canonical KYC field correction can be confirmed', 400);
    }

    const client = await Client.findOne({ clientId: correction.clientId });
    if (!client) throw workflowError('Client not found for this correction', 409);
    const fieldDef = (REQUIRED_KYC_FIELDS[client.type] || []).find(
      (field) => field.key === correction.fieldKey
    );
    if (!fieldDef) throw workflowError('Correction field is not part of the current legal form', 409);
    const currentValue = client.kyc?.[correction.fieldKey];
    if (!hasValue(currentValue)) throw workflowError('A blank KYC field cannot be marked corrected', 409);

    const updated = await KycCorrection.findOneAndUpdate(
      { _id: correction._id, status: 'resubmitted' },
      {
        $set: { status: 'corrected', everFilled: true },
        $unset: { rejectionReason: 1 },
        $push: { history: { status: 'corrected', actor: 'compliance', at: new Date() } },
      },
      { new: true, runValidators: true }
    );
    if (!updated) throw workflowError('KYC correction changed while it was being confirmed', 409);

    // The correction transition is the authoritative approval. Preserve the
    // audit entry when possible; a transient audit failure must not roll the
    // field back to an unreviewed state.
    await Client.updateOne(
      { _id: client._id, type: client.type, [`kyc.${correction.fieldKey}`]: currentValue },
      {
        $push: {
          auditTrail: {
            action: `KYC field "${fieldDef.label}" marked corrected`,
            user: 'Compliance',
            time: new Date().toLocaleString(),
            type: 'approved',
          },
        },
      }
    );
    return updated;
  };

  return runTransactionOrFallback(transactionWork, fallbackWork);
}

// Kept as an eligibility check for callers after a field-level Compliance
// action. Whole-form approval is deliberately *not* performed here: only the
// explicit /verify transition may clear under-review and write approval
// provenance.
async function refreshVerificationFlag(clientOrId) {
  const client = await readCurrentClient(clientOrId);
  if (!client) return false;
  const allFields = REQUIRED_KYC_FIELDS[client.type] || [];
  if (!allFields.length || allFields.some((field) => field.required !== false && !hasValue(client.kyc?.[field.key]))) return false;

  const openCount = await KycCorrection.countDocuments({
    clientId: client.clientId,
    autoGenerated: true,
    status: { $in: OPEN_CORRECTION_STATUSES },
  });
  if (openCount !== 0) return false;

  return true;
}

// Saving an explicit blank is a real draft edit, not "no update". Reopen the
// field so every view can keep it gold and submission/verification stay
// blocked until a non-empty value is saved and resubmitted. Optional questions
// are exempt: leaving one blank is a legitimate answer, not an omission.
async function markBlankKycFields(clientOrId, blankKeys, actorRole) {
  if (!blankKeys || !blankKeys.length) return { updated: 0 };
  const client = await readCurrentClient(clientOrId);
  if (!client) return { updated: 0 };

  const fieldsByKey = new Map(
    (REQUIRED_KYC_FIELDS[client.type] || []).map((field) => [field.key, field])
  );
  let updated = 0;
  for (const key of [...new Set(blankKeys)]) {
    const field = fieldsByKey.get(key);
    if (!field || field.required === false || hasValue(client.kyc?.[key])) continue;
    const result = await KycCorrection.updateOne(
      { clientId: client.clientId, fieldKey: key, autoGenerated: true },
      {
        $set: {
          mandateId: client.clientId,
          issue: `Missing: ${field.label}`,
          page: field.page,
          status: 'needs_correction',
          everFilled: true,
        },
        $setOnInsert: { clientId: client.clientId, fieldKey: key, autoGenerated: true },
        $push: { history: { status: 'needs_correction', actor: actorRole, at: new Date() } },
      },
      { upsert: true }
    );
    updated += (result.modifiedCount || 0) + (result.upsertedCount || 0);
  }
  return { updated };
}

module.exports = {
  OPEN_CORRECTION_STATUSES,
  reconcileKycCorrectionDefinitions,
  syncKycCorrectionsForClient,
  saveKycFields,
  markBlankKycFields,
  submitKycFields,
  flagFieldIncorrect,
  confirmFieldCorrect,
  rejectKycCorrection,
  approveKycCorrection,
  refreshVerificationFlag,
};
